import type { Metadata } from "next";
import { lexend } from "@/app/ui/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "ITjob | Việc làm IT tốt nhất cho bạn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased`}>{children}</body>
    </html>
  );
}
