# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package.json và package-lock.json / yarn.lock
COPY package*.json ./

# Cài dependencies
RUN npm install --frozen-lockfile

# Copy toàn bộ source code
COPY . .

# Build Next.js production
RUN npm run build

# Stage 2: Production
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["npm", "run", "start"]
